/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Betting } from "./Betting";
export type { CommitReveal } from "./CommitReveal";
export type { Stakex } from "./Stakex";
export type { StakingPool } from "./StakingPool";
