import Image from 'next/image';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEtherBalance, useEthers, useSendTransaction } from '@usedapp/core';

import { useState } from 'react';
import { MinFooter, LoadingSpinner, ConnectButton } from '@/components';
import { useCustomCall } from '@/hooks';
import { poolABI, tokenABI } from '@/abis';

import Logo from '@/assets/logo.svg';
import { BsChevronDown } from 'react-icons/bs';

// useful links
// https://goerli.etherscan.io/address/0x6535a4e977885cba7fa99b00ee64d4e7c83fd847#readContract
// https://goerli.etherscan.io/address/0xc1b92cd61e0acaeb4678aa2757fc21ac09555910#code
// https://flowbite.com/docs/forms/input-field/

const Stake = () => {
    const router = useRouter();
    const { account } = useEthers(); // using this for checking connection state
    const etherBalance = useEtherBalance(account); // using this for checking connection state
    const { sendTransaction } = useSendTransaction(); // using this for write to stake, unstake, and claim - useCustomCall for read only stuff
    const [stake, setStake] = useState(true); // true = staking menu, false = rewards menu

    const [stakeAmount, setStakeAmount] = useState<number | string>("");
    const [unstakeAmount, setUnstakeAmount] = useState<number | string>("");

    // {/* https://polygon.lido.fi/ - maybe model it after this */}

    const poolAddress = process.env.NEXT_PUBLIC_STAKING_CONTRACT_ADDRESS;
    const tokenAddress = process.env.NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS;

    const apy = useCustomCall(poolAddress, poolABI, "getAPY", []);
    const balanceHeld = useCustomCall(tokenAddress, tokenABI, "balanceOf", [account ?? "0x0"]); // using 0x0 here to error out if account is null, will be undefined
    const balanceStaked = useCustomCall(poolAddress, poolABI, "getStakedBalance", [account ?? "0x0"]);
    const balanceClaimable = useCustomCall(poolAddress, poolABI, "getUserClaimableRewards", [account ?? "0x0"]);

    // info panel at the bottom - https://tailwindui.com/components/application-ui/overlays/panels (idk this was autogenerated)
    // implement graph and reward query/history in rewards menu

    // maybe add some logic to check if the number is actually a valid amount to unstake / stake on the button press

    const handleUnstakeAmountChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        if(event.target.value.includes(".") || 
           event.target.value.includes(" ") ||
           Number.isNaN(+event.target.value)) return;

        setUnstakeAmount(event.target.value);
    };

    const handleStakeAmountChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        if(event.target.value.includes(".") || 
           event.target.value.includes(" ") ||
           Number.isNaN(+event.target.value)) return;

        setStakeAmount(event.target.value);
    };

    return (
        <>
            <Head>
                <title>Stakex - Staking</title>
				<meta name="description" content="Stakex" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col min-h-screen bg-slate-900">
                <header className='flex p-8 w-full justify-around'>
                    <div className='flex cursor-pointer' onClick={() => { router.push('/').then().catch(console.error) }}>
                        {/* eslint-disable-next-line @typescript-eslint/no-unsafe-assignment */}
                        <Image className='w-10 mr-2' src={Logo} alt='Stakex Logo' />
                        <h2 className='text-2xl flex flex-col justify-center'>Stakex</h2>
                        <p className='text-purple-600 flex pt-2'>
                            &nbsp;Beta
                        </p>
                    </div>
                    <div className='flex'>
                        <ConnectButton display='compact' />
                    </div>
                </header>
                <div className='flex flex-col flex-grow items-center'>
                    <div className='flex flex-col items-center'>
                        <h1 className='text-4xl'>Staking</h1>
                        <p className='text-gray-400'>Earn a percent of platform revenue</p>
                    </div>
                    <div className='flex flex-row items-center bg-gray-900 border-slate-800 border-2 rounded-3xl mt-4'>
                        <a className="flex flex-1 group transition-all duration-300 ease-in-out m-1">
                            <button className='text-white bg-left-bottom bg-gradient-to-r from-blue-500 to-violet-600 bg-[length:0%_2px] bg-no-repeat group-hover:bg-[length:100%_2px] transition-all duration-500 ease-out m-4' onClick={() => setStake(true)}>
                                Stake
                            </button>
                        </a>
                        <p className='m-1'>·</p>
                        <a className="flex flex-1 group transition-all duration-300 ease-in-out m-1 justify-end">
                            <button className='text-white bg-left-bottom bg-gradient-to-r from-blue-500 to-violet-600 bg-[length:0%_2px] bg-no-repeat group-hover:bg-[length:100%_2px] transition-all duration-500 ease-out m-4' onClick={() => setStake(false)}>
                                Rewards
                            </button>
                        </a>
                    </div>
                    {stake ? (
                        <div className='flex flex-col items-center'>
                            <div className='flex flex-col items-center mt-12 w-[70em] justify-around'>
                                <div className='flex flex-row p-10 mx-8 leading-7 bg-gray-800 border-2 rounded-[20px] border-gray-800 gap-2'>
                                    <div className='flex flex-col gap-4 mr-8 w-48'> {/* staking */}
                                        <p className='text-gray-400 text-2xl self-center'>Stake</p>
                                        
                                        <label className='relative inline-flex border border-solid border-slate-500 rounded-2xl items-stretch box-border px-3 cursor-text transition-colors duration-100 ease-in-out w-full self-center'>
                                            <span className='flex items-center flex-shrink-0 cursor-inherit pr-4'>
                                                {/* eslint-disable-next-line @typescript-eslint/no-unsafe-assignment */}
                                                <Image src={Logo} alt='Stakex Logo' width={24} height={24} />
                                            </span>

                                            <span className='font-normal text-base flex flex-grow relative py-4'>
                                                <input className='bg-transparent shadow-none border-transparent outline-none w-full font-normal text-base leading-normal p-0 rounded-none relative top-2' disabled={false} placeholder='0.00' min={0} value={stakeAmount} onChange={handleStakeAmountChange} />
                                                <span className='absolute left-0 top-1/2 text-base leading-tight whitespace-nowrap overflow-hidden text-ellipsis max-w-full transform origin-top translate-y-[-4px] translate-x-[-6px] scale-75 opacity-100 -mt-4 duration-100 ease-in-out'>Amount</span>
                                            </span>

                                            <span className='flex items-center flex-shrink-0 cursor-inherit pl-4'>
                                                <div className='flex items-center'>
                                                    <button className='border-2 border-purple-800 outline-none bg-transparent px-1 bg-purple-800 text-purple-300 opacity-70 rounded-lg' onClick={() => { setStakeAmount(balanceHeld ?? 0) }}>
                                                        <p className='font-bold text-xs p-1'>MAX</p> {/* make this actually functional */}
                                                    </button>
                                                </div>
                                            </span>
                                        </label>

                                        <button className='flex text-white bg-blue-500 p-4 rounded-xl w-full h-16 justify-center' onClick={() => { sendTransaction({ to: poolAddress, data: '0x' }).then().catch(console.error) }}>
                                            <p className='text-l self-center'>Stake</p>
                                        </button>
                                    </div>

                                    {/* separator */}
                                    <div className='border-r-2 border-gray-600 h-auto' />

                                    <div className='flex flex-col gap-4 mx-8 w-48'> {/* unstaking */}
                                        <p className='text-gray-400 text-2xl self-center'>Unstake</p>
                                        <label className='relative inline-flex border border-solid border-slate-500 rounded-2xl items-stretch box-border px-3 cursor-text transition-colors duration-100 ease-in-out w-full self-center'>
                                            <span className='font-normal text-base flex flex-grow relative py-4'>
                                                <input className='bg-transparent shadow-none border-transparent outline-none w-full font-normal text-base leading-normal p-0 rounded-none relative top-2' disabled={false} placeholder='0.00' min={0} value={unstakeAmount} onChange={handleUnstakeAmountChange} />
                                                <span className='absolute left-0 top-1/2 text-base leading-tight whitespace-nowrap overflow-hidden text-ellipsis max-w-full transform origin-top translate-y-[-4px] translate-x-[-6px] scale-75 opacity-100 -mt-4 duration-100 ease-in-out'>Amount</span>
                                            </span>

                                            <span className='flex items-center flex-shrink-0 cursor-inherit pl-4'>
                                                <div className='flex items-center'>
                                                    <button className='border-2 border-purple-800 outline-none bg-transparent px-1 bg-purple-800 text-purple-300 opacity-70 rounded-lg' onClick={() => { setUnstakeAmount(balanceStaked ?? 0) }}>
                                                        <p className='font-bold text-xs p-1'>MAX</p> {/* make this actually functional */}
                                                    </button>
                                                </div>
                                            </span>
                                        </label>

                                        <button className='flex text-white bg-blue-500 p-4 rounded-xl w-full h-16 justify-center' onClick={() => { sendTransaction({ to: poolAddress, data: '0x' }).then().catch(console.error) }}>
                                            <p className='text-l self-center'>Unstake</p>
                                        </button>
                                    </div>

                                    {/* separator */}
                                    <div className='border-r-2 border-gray-600 h-auto' />

                                    <div className='flex flex-col gap-4 ml-8 w-48 justify-between'> {/* claim */}
                                        <p className='text-gray-400 text-2xl self-center'>Claim</p>
                                        <p className='text-white text-sm self-center'>Total Claimable: {balanceClaimable ?? 0.0}</p>
                                        {account && etherBalance ? ( // make this apply to the whole panel instead of just the claim button (maybe blur the background too?)
                                            <div className='flex'>
                                                <button className='flex text-white bg-blue-500 p-4 rounded-xl w-full h-16 justify-center mt-1' onClick={() => { sendTransaction({ to: poolAddress, data: '0x' }).then().catch(console.error) }}>
                                                    <p className='text-l self-center'>Claim</p>
                                                </button>
                                            </div>
                                        ) : (
                                            <div className='flex opacity-70 bg-slate-500 border-[1px] border-slate-600 rounded-xl w-full justify-center h-16 mt-1'>
                                                {/* diagonal line */}
                                                <div className='border-r-2 border-slate-400 h-12 transform rotate-45 relative self-center' />
                                                <div className='border-r-2 border-slate-400 h-12 transform rotate-45 relative left-12 self-center' />
                                                <p className='text-white self-center z-50 font-bold text-shadow shadow-slate-200'>Please Connect</p>
                                                <div className='border-r-2 border-slate-400 h-12 transform rotate-45 relative self-center' />
                                            </div>
                                        )}
                                    </div>
                                </div>

                                <div className='flex flex-row gap-4 p-4 mt-12 rounded-xl w-full bg-slate-700 justify-between'>
                                    <p className='text-slate-400'>FAQ</p>
                                    {/* going to be a drop down into an accordian is what im thinkin */}
                                    <button className='flex' onClick={() => {console.log("cream")}}>
                                        <BsChevronDown size={24} />
                                    </button>
                                </div>
                            </div>
                        </div>
                    ) : (
                        /* need to find a good graphing lib and maybe write a microservice to get the apy at a specific time everyday. */
                        <div className='flex flex-row items-center mt-12 w-[40em] justify-around'>
                            <div className='flex flex-col p-10 mx-8 leading-7 bg-gray-800 border-2 rounded-[20px] border-gray-800'> {/* rewards */}
                                <p className='text-gray-400'>Rewards Available</p>
                                <p className='text-white'>0.00</p>
                            </div>
                            <div className='flex flex-col p-10 mx-8 leading-7 bg-gray-800 border-2 rounded-[20px] border-gray-800'>
                                <p className='text-gray-400'>APY over Time</p>
                                {apy ? (
                                    <div className='flex flex-col items-center'>
                                        {apy} <span>% APY</span>
                                    </div>
                                ) : 
                                    <div role="status" className="max-w-sm animate-pulse">
                                        <div className="h-3 bg-gray-200 rounded-full dark:bg-gray-700 w-8 mb-4" />
                                        <span className="sr-only">
                                            <LoadingSpinner size={16} /> {/* Change name to skeleton */}
                                        </span>
                                    </div>
                                }
                            </div>
                        </div>
                    )}
                </div>
                <div className='flex flex-col mt-auto w-full'>
                    <MinFooter />
                </div>
            </main>
        </>
    )
}

export default Stake;